# Generated by Django 5.2.7 on 2025-10-24 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_skills', models.TextField(null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.course')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_skills', models.TextField()),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.skill')),
            ],
        ),
    ]
